### PR TITLE
Typos and consistency improvements.

### PR DESCRIPTION
**Pull request by jonathancross**

### CODE REVIEW

**Comment by jonathancross** [comment]
@josephpoon @Roasbeef Any concerns / corrections you'd like to see here?

**Review by Roasbeef — APPROVED** [review]

**Comment by jonathancross** [comment]
@josephpoon Anything more you'd like to see here?

**Comment by jonathancross** [comment]
Ping  :-)  @Roasbeef Doesn't look like @josephpoon  is going to respond here.

**Comment by jonathancross** [comment]
Hmmm, seems this repo is ignored.
Too bad...

**Pull request closed without merging**
